### ISSUE TITLE
[head posture] Wrong 3d data when face is located on side

### ISSUE THREAD

**Issue by remmel** [Rassibassi/mediapipeDemos#7] opened 2022-01-05 18:16 UTC
Hi,

When I'm in the center of the image, the 3d result is pretty accurate (comparing with the kinect depth). But when I'm on the side, something is wrong. 
The image below has been captured with head_posture (same code like github, only mp_face_mesh.FaceMesh commented, as not in last version anymore). In **blue** is the normal of my nose calculated. In **red** is what **I would expect**, I've added in gimp.

The blue line should go on the left, on the same side than the less visible ear.

![VideoSource - FPS: 30 0_screenshot_05 01 2022_](https://user-images.githubusercontent.com/937836/148264263-19c0d062-f7ff-4b30-925b-de351544b56a.png)

To give a little bit more details, when I reproject the image (where I'm on the side) on the mesh in a [3d space](https://github.com/remmel/mediapipeDemos/blob/ec2407c1b33b6f43e4afeede3384bf01538e0f15/head_posture_static.py#L124) (without using the uv - `face_landmarks.landmark[idx].x and y` ) I don't get the same texture than using directly those uv. Which make me think that projecting x,y,z (from `model_points`) to u,v using R,t (`rotation_vector, translation_vector`) won't give initial u,v values

Thanks!

**Comment by Rassibassi** [comment] 2022-01-07 08:45
Hej,

nice spotting this one.

First, I updated `head_posture.py` with something I wanted to do for a long time. Now the script does not use `solvePnP` anymore, but only the result from mediapipe. Yet, all numerical numbers are the same, we just save some extra computation.

Let's talk about the _not matching blue and red line_ of the image posted from yourself. The error only occurs close to the edges of the image, and with my camera the problem is less dominant. I suspect that it is due to [the **radial distortion** of your camera](https://docs.opencv.org/3.4/dc/dbb/tutorial_py_calibration.html) [1].

> Radial distortion becomes larger the farther points are from the center of the image.

Yet, cv2 has a compensation technique for that, which includes a camera calibration, when you follow the link above.

Let me know if this solves it for you :)

Best wishes,
Rasmus

[1] https://docs.opencv.org/3.4/dc/dbb/tutorial_py_calibration.html

**Comment by remmel** [comment] 2022-01-07 09:44
Hi! I was also checking that this morning, and this is not because of the camera distortion, this is because `np.array([(0.0, 0.0, 25.0)])` is incorrect. As the center of the 3d face is not the nose but "inside the brain"

To check it, project the center of the mesh (0,0,0) and display it! 

```
(beg_point2D, jacobian) = cv2.projectPoints(
                    np.array([(0.0, 0.0, 0.0)]), #noseEndPoints3D
                    rotation_vector,
                    translation_vector,
                    camera_matrix,
                    dist_coeff,
                )

# set p1 with that instead
p1 = (int(beg_point2D[0][0][0]), int(beg_point2D[0][0][1]))
```

**Comment by Rassibassi** [comment] 2022-01-07 10:06
You mean like this:
```python
(nose_pointer2D, jacobian) = cv2.projectPoints(
    np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 25.0]]),
    mp_rotation_vector,
    mp_translation_vector,
    camera_matrix,
    dist_coeff,
)

p1 = (int(nose_pointer2D[0][0][0]), int(nose_pointer2D[0][0][1]))
p2 = (int(nose_pointer2D[1][0][0]), int(nose_pointer2D[1][0][1]))
```

It does not change the tilt of the nose pointing line on my side.

**Comment by remmel** [comment] 2022-01-07 10:34
Check the image below (with corresponding code)
- Red : your incorrect line
- Blue : the correct pinocchio nose
- Black : line going from the center/brain to your incorrect end (0,0,25)


![VideoSource - FPS: 30 0_screenshot_07 01 2022](https://user-images.githubusercontent.com/937836/148531035-77482b10-3eaf-4af2-af89-e8118792539a.png)

```
points3D = np.array([
                    (0.0, 0.0, 0.0), #brain
                    model_points[0], #nose begin
                    model_points[0]*5, #nose end
                    (0.0, 0.0, 25.0), #brain end
                ])

                (point2D, jacobian) = cv2.projectPoints(
                    points3D,
                    rotation_vector,
                    translation_vector,
                    camera_matrix,
                    dist_coeff,
                )

                p1Brain = (int(point2D[0][0][0]), int(point2D[0][0][1])) #brain
                p2NoseBeg = (int(point2D[1][0][0]), int(point2D[1][0][1])) # same than (int(image_points[0][0]), int(image_points[0][1]))
                p3NoseEnd = (int(point2D[2][0][0]), int(point2D[2][0][1]))
                p4BrainEnd = (int(point2D[3][0][0]), int(point2D[3][0][1]))

                frame = cv2.line(frame, p2NoseBeg, p4BrainEnd, (0, 0, 255), 2)  # original incorrect line
                frame = cv2.line(frame, p2NoseBeg, p3NoseEnd, (255, 0, 0), 2) # correct pinocchio nose
                frame = cv2.line(frame, p1Brain, p4BrainEnd, (0, 0, 0), 2) # line going from the brain to the original end
```

**Comment by remmel** [comment] 2022-01-07 10:46
If the nose would have been the center of the 3d face, its face_landmarks.landmark.z would have be 0 (face_landmarks.landmark.x and y are in reality u,v webcam coordinates)

**Comment by Rassibassi** [comment] 2022-01-07 10:59
I see now! Thanks! I pushed a fix :)

**Closed** 2022-01-07 11:00 UTC
